; Generated by v06c-asm-export (Stage 6.17)
; ROM: TESTAY.ROM
; Size: 3712 bytes
; SHA-256: 8170faa43034a3ed8ca573be3a854184cdd1751457e74befad83e5289f4d3db5

	org	0100h

	include	"layout.asm"

; Read-only views, not part of the build:
;   include "code/code.asm"
;   include "data/data.asm"
