#!/usr/bin/env python3
# Stage 12 layout generator: builds asm/putup_new.asm (address-exact) + asm/bin/gap_*.bin
# Reads RDB + asm file header comments (authoritative addr/size). Gap bytes are taken
# VERBATIM from src/putup.rom (they are data, not disassembly). No MCP output is used.
import json, os, re, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ASM  = os.path.join(ROOT, "asm")
BIN  = os.path.join(ASM, "bin")
ROM  = os.path.join(ROOT, "src", "putup.rom")
RDB  = os.path.join(ROOT, "src", "putup.rdb")
ORG  = 0x0100
SIZE = 17664
END  = ORG + SIZE   # 0x4600

rom = open(ROM, "rb").read()
assert len(rom) == SIZE
RDBP=os.path.join(ROOT,"src","putup.rdb")
_r=json.load(open(RDBP,encoding="utf-8"))
rdb_addr={o["name"]:int(o["address"],16) for o in _r["objects"]}
_szp=os.path.join(ROOT,"tools","sizes.json")
real_sz=json.load(open(_szp)) if os.path.exists(_szp) else {}  # assembler-measured emit lengths

addr_re  = re.compile(r"Адрес:\s*0x([0-9A-Fa-f]{1,4})")
size_re  = re.compile(r"Размер:\s*(\d+)")

def file_bytesize(path, declared):
    """If the file is a pure INCBIN wrapper, the .bin length is authoritative."""
    txt = open(path, encoding="utf-8").read()
    bins = re.findall(r'INCBIN\s+"([^"]+)"', txt)
    if bins and not re.search(r'^\s*DEF', txt, re.M):
        return sum(os.path.getsize(os.path.join(ASM, b)) for b in bins)
    return declared

# gather emit files with declared addr/size
emit = {}
for fn in sorted(os.listdir(ASM)):
    if not fn.endswith(".asm") or fn == "var_ram_symbols.asm":
        continue
    path = os.path.join(ASM, fn)
    head = "\n".join(open(path, encoding="utf-8").read().splitlines()[:12])
    a = addr_re.search(head)
    if not a:
        print("  no addr:", fn, "-> skipped (RAM/EQU)"); continue
    s = size_re.search(head)
    declared = int(s.group(1)) if s else -1
    addr = int(a.group(1), 16)
    addr = rdb_addr.get(fn[:-4], addr)  # canonical RDB wins
    if not (ORG <= addr < END):
        print("  out of image:", fn, hex(addr)); continue
    nm=fn[:-4]
    emit[nm] = (addr, real_sz.get(nm, file_bytesize(path, declared)))

# sort + drop overlaps (nested duplicates like data_level_02..15 inside maps)
items = sorted(emit.items(), key=lambda kv: kv[1][0])
kept = []
cov = ORG
for name, (a, sz) in items:
    if a < cov:
        print("  overlap-skipped (dup):", name, hex(a)); continue
    kept.append((name, a, sz))
    cov = a + sz

# build ordered segments: emit slots + gap complements
segs = []
cur = ORG
for name, a, sz in kept:
    if a > cur:
        segs.append(("gap", cur, a - cur))
    segs.append(("emit", a, sz, name))
    cur = a + sz
if cur < END:
    segs.append(("gap", cur, END - cur))

os.makedirs(BIN, exist_ok=True)
lines = []
lines.append("; PUTUP_NEW.ROM - address-exact reconstruction of src/putup.rom")
lines.append("; GENERATED by tools/gen_layout.py -- do not hand-edit this file.")
lines.append("; org 0x0100; every exported object is placed at its ORIGINAL address;")
lines.append("; inter-object gaps (uncaptured code / RAM-var storage / Stage-11 music")
lines.append("; data without an asm file) are filled VERBATIM from src/putup.rom.")
lines.append("")
lines.append("    org 0h")
lines.append('    include "var_ram_symbols.asm"')
lines.append("")
gapcount = 0
gapbytes = 0
for seg in segs:
    if seg[0] == "emit":
        _, a, sz, name = seg
        lines.append("; --- emit %s @0x%04X (%d bytes) ---" % (name, a, sz))
        lines.append("    defs 0x%04X - $ ; align" % a)
        lines.append('    include "%s.asm"' % name)
        lines.append("")
    else:
        _, a, sz = seg
        binname = "gap_%04X_%04X.bin" % (a, a + sz)
        with open(os.path.join(BIN, binname), "wb") as f:
            f.write(rom[a - ORG : a - ORG + sz])
        gapcount += 1; gapbytes += sz
        lines.append("; --- gap 0x%04X..0x%04X (%d bytes) from original image ---" % (a, a + sz, sz))
        lines.append("    defs 0x%04X - $ ; align" % a)
        lines.append('    INCBIN "bin/%s"' % binname)
        lines.append("")
lines.append("; image end @0x%04X" % END)
open(os.path.join(ASM, "putup_new.asm"), "w", encoding="utf-8").write("\n".join(lines) + "\n")

emitbytes = sum(s for s in kept for s in [s[2]]) if False else sum(k[2] for k in kept)
print("kept emit files: %d (%d bytes)" % (len(kept), emitbytes))
print("gaps: %d (%d bytes) -> asm/bin/gap_*.bin" % (gapcount, gapbytes))
print("total: %d bytes (expect %d)" % (emitbytes+gapbytes, SIZE))
