; Generated by v06c-asm-export (Stage 6.17)
; ROM: riseout.rom
; Size: 20480 bytes
; SHA-256: c265014b3db42ccc3454c8c9e6a1d9cb47f43e00c373f494ece1b47f675a6991

	org	0100h

	include	"layout.asm"

; Read-only views, not part of the build:
;   include "code/code.asm"
;   include "data/data.asm"
