; Data section — generated by v06c-asm-export
; View only: the build consumes layout.asm (Stage 6.23 §2.2)
; Regions here are the same byte runs layout.asm emits

; Рабочий указатель текущего потока (мишень LHLD/SHLD 0x0103). Вписан в код сразу за входным JMP; самомодифицируемые данные.
var_cur_stream_ptr:
	defb	0FBh,0C9h

; Базовый указатель паттернов канала A (заполняется из заголовка трека через func_store_de_to_bc, LXI B,0x045E).
var_pattern_base_A:
	defb	20h,20h

; Базовый указатель паттернов/длительностей канала B (LXI B,0x0460).
var_pattern_base_B:
	defb	70h,72h

; Базовый указатель паттернов канала C (LXI B,0x0462).
var_pattern_base_C:
	defb	69h,77h

; Базовый указатель pitch-таблицы (вычисляется в init через func_add_selfmod_base, SHLD 0x0464).
var_pitch_table_base:
	defb	65h,74h

; Темп трека — значение перезагрузки счётчика (читается из [0x0657] в init).
var_tempo:
	defb	20h

; Счётчик делителя темпа (LDA/DCR/STA 0x0467 в func_player_tick).
var_tempo_counter:
	defb	20h

; Длина трека (из заголовка, INR; сравнение в func_pattern_fetch).
var_song_length:
	defb	6Dh

; Текущий указатель нотного потока канала A (иниц. 0x046F; SHLD 0x0469).
var_stream_ptr_A:
	defb	69h,7Bh

; Текущий указатель нотного потока канала B.
var_stream_ptr_B:
	defb	65h,20h

; Текущий указатель нотного потока канала C.
var_stream_ptr_C:
	defb	20h,20h

; Таблица состояния 3 каналов (0x046F..0x049B). Записи по ~10 байт: базы 0x0472/0x047C/0x0486 (указатель потока, питч, громкость, длительность, флаги). Инициализация: 1-й байт 0xFF, остальные 00.
data_channel_state:
	defb	20h,20h,74h,61h,6Ch,6Fh,6Eh,75h
	defb	20h,20h,20h,21h,20h,21h,20h,21h
	defb	21h,20h,20h,58h,41h,2Dh,58h,41h
	defb	2Dh,58h,41h,20h,20h,20h,21h,21h
	defb	21h,4Fh,54h,20h,72h,61h,7Ah,77h
	defb	65h,64h,7Eh,69h,6Bh

; Рабочий регистр заметки/параметра для вывода в AY (STA 0x049C в обработчиках; читается func_ay_write_registers как старшая точка обхода).
var_ay_note_reg:
	defb	61h

; 12-байтовый XOR-ключ дешифровки музыкальных трюков: 77 6C 67 D0 B6 6A 7F 7F 3F B3 38 9F (используется func_xor_decrypt_loop, HL=0x0553).
data_xor_key:
	defb	77h,6Ch,67h,0D0h,0B6h,6Ah,7Fh,7Fh
	defb	3Fh,0B3h,38h,9Fh

; Мастер-таблица периодов тона AY: 96 16-битных убывающих значений (от 0x0EF8 до 0x000F). Индексируется в func_pitch_calc (LXI H,0x057A, шаг 2).
music_pitch_table:
	defb	0F8h,0Eh,10h,0Eh,60h,0Dh,80h,0Ch
	defb	0D8h,0Bh,28h,0Bh,88h,0Ah,0F0h,09h
	defb	60h,09h,0E0h,08h,58h,08h,0E0h,07h
	defb	7Ch,07h,08h,07h,0B0h,06h,40h,06h
	defb	0ECh,05h,94h,05h,44h,05h,0F8h,04h
	defb	0B0h,04h,70h,04h,2Ch,04h,0F0h,03h
	defb	0BEh,03h,84h,03h,58h,03h,20h,03h
	defb	0F6h,02h,0CAh,02h,0A2h,02h,7Ch,02h
	defb	58h,02h,38h,02h,16h,02h,0F8h,01h
	defb	0DFh,01h,0C2h,01h,0ACh,01h,90h,01h
	defb	7Bh,01h,65h,01h,51h,01h,3Eh,01h
	defb	2Ch,01h,1Ch,01h,0Bh,01h,0FCh,00h
	defb	0EFh,00h,0E1h,00h,0D6h,00h,0C8h,00h
	defb	0BDh,00h,0B2h,00h,0A8h,00h,9Fh,00h
	defb	96h,00h,8Eh,00h,85h,00h,7Eh,00h
	defb	77h,00h,70h,00h,6Bh,00h,64h,00h
	defb	5Eh,00h,59h,00h,54h,00h,4Fh,00h
	defb	4Bh,00h,47h,00h,42h,00h,3Fh,00h
	defb	3Bh,00h,38h,00h,35h,00h,32h,00h
	defb	2Fh,00h,2Ch,00h,2Ah,00h,27h,00h
	defb	25h,00h,23h,00h,21h,00h,1Fh,00h
	defb	1Dh,00h,1Ch,00h,1Ah,00h,19h,00h
	defb	17h,00h,16h,00h,15h,00h,13h,00h
	defb	12h,00h,11h,00h,10h,00h,0Fh,00h

; Текст (автор/контакт): "(833)62-74-48 VICTOR SATURO".
str_credit_contact:
	defb	28h,38h,33h,33h,29h,36h,32h,2Dh
	defb	37h,34h,2Dh,34h,38h,20h,56h,49h
	defb	43h,54h,4Fh,52h,20h,53h,41h,54h
	defb	54h,41h,52h

; Заголовок трека: [0x0657]=темп, далее слова-указатели баз каналов (чита func_read_word_de в func_init_song).
data_song_header:
	defb	4Fh,56h,08h,33h,03h,48h,03h

; Текст: "SONG BY ST COMPILE" (продолжение "COMPILER").
str_credit_song:
	defb	37h,05h,53h,4Fh,4Eh,47h,20h,42h
	defb	59h,20h,53h,54h,20h,43h,4Fh,4Dh
	defb	50h,49h

; Таблицы параметров трека после заголовка (16-битные значения 0x8000/0x0F80 — громкость/огибающие/маски), перед нотными потоками.
data_song_params:
	defb	4Ch,45h,0D5h,08h,01h,0Fh,00h,00h
	defb	0Eh,80h,00h,0Dh,80h,00h,0Ch,80h
	defb	00h,0Bh,80h,00h,0Ah,80h,00h,09h
	defb	80h,00h,08h,80h,00h,07h,80h,00h
	defb	06h,80h,00h,05h,80h,00h,04h,80h
	defb	00h,03h,80h,00h,02h,80h,00h,01h
	defb	80h,00h,00h,00h,00h,00h,00h,00h
	defb	00h,00h,00h,00h,00h,00h,00h,00h
	defb	00h,00h,00h,00h,00h,00h,00h,00h
	defb	00h,00h,00h,00h,00h,00h,00h,00h
	defb	00h,00h,00h,00h,00h,00h,00h,00h
	defb	00h,00h,00h,00h,00h,00h,00h,00h
	defb	00h,00h,00h,00h,00h,00h,00h,03h
	defb	0Fh,80h,00h,0Fh,80h,00h,0Eh,80h
	defb	00h,0Dh,80h,00h,0Ch,80h,00h,0Bh
	defb	80h,00h,0Ah,80h,00h,09h,80h,00h
	defb	09h,80h,00h,09h,80h,00h,09h,80h
	defb	00h,09h,80h,00h,09h,80h,00h,09h
	defb	80h,00h

; Нотные потоки 3 каналов + XOR-зашифрованные 12-байтные трюки. Слот трюка = 0x0700+2*lo(адреса возврата) (func_thunk_slot_addr). Чтение только, writes во время дешифровки (инволютивный XOR).
music_streams:
	defb	09h,80h,00h,09h,80h,00h,09h,80h
	defb	00h,09h,80h,00h,09h,80h,00h,09h
	defb	80h,00h,09h,80h,00h,09h,80h,00h
	defb	09h,80h,00h,09h,80h,00h,09h,80h
	defb	00h,09h,80h,00h,09h,80h,00h,09h
	defb	80h,00h,09h,80h,00h,09h,80h,00h
	defb	09h,80h,00h,09h,80h,00h,1Ah,05h
	defb	04h,0Eh,00h,00h,0Eh,80h,00h,0Dh
	defb	80h,00h,0Dh,80h,00h,0Ch,80h,00h
	defb	0Ch,80h,00h,0Ch,80h,00h,0Ch,80h
	defb	00h,0Ch,80h,00h,0Ch,80h,00h,0Ch
	defb	80h,00h,0Ch,80h,00h,0Ch,80h,00h
	defb	0Ch,80h,00h,0Ch,80h,00h,0Ch,80h
	defb	00h,0Ch,80h,00h,0Ch,80h,03h,0Ch
	defb	80h,06h,0Ch,80h,03h,0Ch,80h,00h
	defb	0Ch,0A0h,03h,0Ch,0A0h,06h,0Ch,0A0h
	defb	03h,0Ch,80h,00h,0Ch,80h,03h,0Ch
	defb	80h,06h,0Ch,80h,03h,0Ch,80h,00h
	defb	0Ch,0A0h,03h,0Ch,0A0h,06h,0Ch,0A0h
	defb	03h,18h,07h,06h,0Fh,00h,00h,0Fh
	defb	80h,01h,0Eh,80h,02h,0Dh,80h,01h
	defb	0Ch,80h,00h,0Bh,0A0h,02h,0Ah,0A0h
	defb	04h,09h,0A0h,02h,08h,80h,00h,07h
	defb	80h,02h,06h,80h,04h,07h,80h,02h
	defb	08h,80h,00h,09h,0A0h,01h,0Ah,0A0h
	defb	02h,09h,0A0h,01h,08h,80h,00h,07h
	defb	80h,01h,06h,80h,02h,05h,80h,01h
	defb	04h,80h,00h,03h,0A0h,02h,02h,0A0h
	defb	04h,01h,0A0h,02h,00h,80h,00h,00h
	defb	80h,02h,00h,80h,04h,00h,80h,02h
	defb	00h,80h,00h,00h,0A0h,01h,00h,0A0h
	defb	02h,00h,0A0h,01h,00h,00h,09h,0Fh
	defb	80h,00h,0Fh,80h,00h,0Eh,80h,00h
	defb	0Dh,80h,00h,0Ch,80h,00h,0Bh,80h
	defb	00h,0Ah,80h,00h,09h,80h,00h,08h
	defb	80h,00h,07h,80h,00h,06h,80h,00h
	defb	05h,80h,00h,04h,80h,00h,03h,80h
	defb	00h,02h,80h,00h,01h,80h,00h,00h
	defb	80h,00h,00h,80h,00h,00h,80h,00h
	defb	00h,80h,00h,00h,80h,00h,00h,80h
	defb	00h,00h,80h,00h,00h,80h,00h,00h
	defb	80h,00h,00h,80h,00h,00h,80h,00h
	defb	00h,80h,00h,00h,80h,00h,00h,80h
	defb	00h,00h,80h,00h,00h,80h,00h,00h
	defb	00h,0Ah,0Fh,80h,00h,0Eh,80h,00h
	defb	0Dh,80h,00h,0Ch,80h,00h,0Bh,80h
	defb	00h,0Ah,80h,00h,09h,80h,00h,08h
	defb	80h,00h,07h,80h,00h,06h,80h,00h
	defb	05h,80h,00h,04h,80h,00h,03h,80h
	defb	00h,02h,80h,00h,01h,80h,00h,00h
	defb	00h,00h,00h,00h,00h,00h,00h,00h
	defb	00h,00h,00h,00h,00h,00h,00h,00h
	defb	00h,00h,00h,00h,00h,00h,00h,00h
	defb	00h,00h,00h,00h,00h,00h,00h,00h
	defb	00h,00h,00h,00h,00h,00h,00h,00h
	defb	00h,00h,00h,00h,00h,00h,00h,00h
	defb	00h,00h,00h,00h,0Eh,0Fh,0A0h,0C8h
	defb	2Dh,0A0h,58h,4Bh,0A0h,4Ch,69h,0A0h
	defb	40h,87h,0A0h,34h,00h,00h,00h,00h
	defb	00h,00h,00h,00h,00h,00h,00h,00h
	defb	00h,00h,00h,00h,00h,00h,00h,00h
	defb	00h,00h,00h,00h,00h,00h,00h,00h
	defb	00h,00h,00h,00h,00h,00h,00h,00h
	defb	00h,00h,00h,00h,00h,00h,00h,00h
	defb	00h,00h,00h,00h,00h,00h,00h,00h
	defb	00h,00h,00h,00h,00h,00h,00h,00h
	defb	00h,00h,00h,00h,00h,00h,00h,00h
	defb	00h,00h,00h,00h,00h,00h,00h,00h
	defb	00h,00h,00h,00h,00h,00h,00h,0Fh
	defb	0Fh,22h,1Eh,0Fh,20h,96h,0Eh,20h
	defb	5Ah,0Eh,20h,0D2h,0Dh,20h,96h,1Dh
	defb	20h,0Eh,0Ch,20h,0D2h,1Ch,20h,4Ah
	defb	1Bh,20h,0Eh,1Bh,20h,86h,00h,00h
	defb	00h,00h,00h,00h,00h,00h,00h,00h
	defb	00h,00h,00h,00h,00h,00h,00h,00h
	defb	00h,00h,00h,00h,00h,00h,00h,00h
	defb	00h,00h,00h,00h,00h,00h,00h,00h
	defb	00h,00h,00h,00h,00h,00h,00h,00h
	defb	00h,00h,00h,00h,00h,00h,00h,00h
	defb	00h,00h,00h,00h,00h,00h,00h,00h
	defb	00h,00h,00h,00h,00h,00h,00h,00h
	defb	00h,00h,09h,02h,00h,01h,00h,03h
	defb	00h,03h,00h,04h,00h,04h,00h,05h
	defb	00h,05h,00h,04h,00h,04h,00h,00h
	defb	00h,00h,00h,00h,00h,00h,00h,00h
	defb	00h,00h,00h,00h,00h,00h,00h,00h
	defb	00h,00h,00h,00h,00h,00h,00h,00h
	defb	00h,00h,00h,00h,00h,00h,00h,00h
	defb	01h,0F8h,0FBh,00h,0F8h,0FBh,00h,0F8h
	defb	0FBh,00h,0F8h,0FBh,00h,0F8h,0FBh,00h
	defb	0F8h,0FBh,00h,0F8h,0FBh,00h,0F8h,0FBh
	defb	00h,0F8h,0FBh,00h,0F8h,0FBh,00h,0F8h
	defb	0FBh,02h,0F9h,0FDh,00h,0F9h,0FDh,00h
	defb	0F9h,0FDh,00h,0F9h,0FDh,00h,0F9h,0FDh
	defb	00h,0F9h,0FDh,00h,0F9h,0FDh,00h,0F9h
	defb	0FDh,00h,0F9h,0FDh,00h,0F9h,0FDh,00h
	defb	0F9h,0FDh,03h,0F7h,0FCh,00h,0F7h,0FCh
	defb	00h,0F7h,0FCh,00h,0F7h,0FCh,00h,0F7h
	defb	0FCh,00h,0F7h,0FCh,00h,0F7h,0FCh,00h
	defb	0F7h,0FCh,00h,0F7h,0FCh,00h,0F7h,0FCh
	defb	00h,0F7h,0FCh,04h,00h,07h,0Ch,00h
	defb	07h,0Ch,00h,07h,0Ch,00h,07h,0Ch
	defb	00h,07h,0Ch,00h,07h,0Ch,00h,07h
	defb	0Ch,00h,07h,0Ch,00h,07h,0Ch,00h
	defb	07h,0Ch,00h,07h,05h,0Ch,0Ch,00h
	defb	00h,00h,00h,00h,00h,00h,00h,00h
	defb	00h,00h,00h,00h,00h,00h,00h,00h
	defb	00h,00h,00h,00h,00h,00h,00h,00h
	defb	00h,00h,00h,00h,00h,07h,0F7h,0FCh
	defb	01h,0F7h,0FCh,01h,0F7h,0FCh,01h,0F7h
	defb	0FCh,01h,0F7h,0FCh,01h,0F7h,0FCh,01h
	defb	0F7h,0FCh,01h,0F7h,0FCh,01h,0F7h,0FCh
	defb	01h,0F7h,0FCh,01h,0F7h,0FCh,08h,00h
	defb	18h,00h,0Ch,00h,00h,00h,0Ch,00h
	defb	00h,00h,0Ch,00h,00h,00h,0Ch,00h
	defb	00h,00h,0Ch,00h,00h,00h,0Ch,00h
	defb	00h,00h,0Ch,00h,00h,00h,0Ch,09h
	defb	0F4h,00h,13h,00h,00h,00h,00h,00h
	defb	00h,00h,00h,00h,00h,00h,00h,00h
	defb	00h,00h,00h,00h,00h,00h,00h,00h
	defb	00h,00h,00h,00h,00h,00h,00h,00h
	defb	0Ah,0F8h,0FDh,00h,0F8h,0FDh,00h,0F8h
	defb	0FDh,00h,0F8h,0FDh,00h,0F8h,0FDh,00h
	defb	0F8h,0FDh,00h,0F8h,0FDh,00h,0F8h,0FDh
	defb	00h,0F8h,0FDh,00h,0F8h,0FDh,00h,0F8h
	defb	0FDh,0Bh,0F9h,0FCh,00h,0F9h,0FCh,00h
	defb	0F9h,0FCh,00h,0F9h,0FCh,00h,0F9h,0FCh
	defb	00h,0F9h,0FCh,00h,0F9h,0FCh,00h,0F9h
	defb	0FCh,00h,0F9h,0FCh,00h,0F9h,0FCh,00h
	defb	0F9h,0FCh,0Ch,0F7h,0FBh,00h,0F7h,0FBh
	defb	00h,0F7h,0FBh,00h,0F7h,0FBh,00h,0F7h
	defb	0FBh,00h,0F7h,0FBh,00h,0F7h,0FBh,00h
	defb	0F7h,0FBh,00h,0F7h,0FBh,00h,0F7h,0FBh
	defb	00h,0F7h,0FBh,0Dh,0F4h,0F4h,00h,00h
	defb	00h,00h,00h,00h,00h,00h,00h,00h
	defb	00h,00h,00h,00h,00h,00h,00h,00h
	defb	00h,00h,00h,00h,00h,00h,00h,00h
	defb	00h,00h,00h,00h,0Eh,13h,0Ch,00h
	defb	00h,00h,00h,00h,00h,00h,00h,00h
	defb	00h,00h,00h,00h,00h,00h,00h,00h
	defb	00h,00h,00h,00h,00h,00h,00h,00h
	defb	00h,00h,00h,00h,00h,0Fh,00h,0FFh
	defb	0FEh,0FDh,0FCh,0FBh,0FAh,0F9h,0F8h,0F7h
	defb	0F6h,0F5h,0F4h,0F3h,0F2h,0F1h,00h,00h
	defb	00h,00h,00h,00h,00h,00h,00h,00h
	defb	00h,00h,00h,00h,00h,00h,01h,5Bh
	defb	05h,0BFh,05h,04h,06h,02h,5Bh,05h
	defb	0B6h,06h,04h,06h,03h,5Bh,05h,0FAh
	defb	06h,04h,06h,04h,42h,07h,0A6h,07h
	defb	0E9h,07h,05h,5Bh,05h,9Bh,08h,04h
	defb	06h,0FFh,0A1h,61h,75h,13h,1Fh,6Ah
	defb	13h,61h,13h,1Fh,13h,6Ah,13h,61h
	defb	1Fh,13h,1Fh,6Ah,13h,61h,13h,1Fh
	defb	13h,6Ah,13h,61h,1Fh,0Ch,18h,6Ah
	defb	0Ch,61h,0Ch,18h,0Ch,6Ah,0Ch,61h
	defb	18h,0Eh,1Ah,6Ah,0Eh,61h,0Eh,1Ah
	defb	0Eh,6Ah,0Eh,61h,1Ah,13h,1Fh,6Ah
	defb	13h,61h,13h,1Fh,13h,6Ah,13h,61h
	defb	1Fh,13h,1Fh,6Ah,13h,61h,13h,1Fh
	defb	13h,6Ah,13h,61h,1Fh,0Ch,18h,6Ah
	defb	0Ch,61h,0Ch,18h,0Ch,6Ah,0Ch,61h
	defb	18h,0Eh,1Ah,6Ah,0Eh,61h,0Eh,1Ah
	defb	0Eh,6Ah,0Eh,61h,1Ah,0FFh,0A1h,63h
	defb	74h,3Bh,0A2h,3Ch,0A5h,3Eh,0A1h,3Bh
	defb	0A2h,3Ch,0A3h,3Eh,0A2h,40h,0A1h,3Eh
	defb	0A2h,3Ch,0A5h,37h,0A1h,73h,42h,42h
	defb	42h,0A2h,71h,43h,0A1h,43h,73h,42h
	defb	42h,74h,3Bh,0A2h,3Ch,0A5h,3Eh,0A1h
	defb	3Bh,0A2h,3Ch,0A3h,3Eh,0A2h,40h,0A1h
	defb	3Eh,0A2h,3Ch,0A5h,37h,0A1h,73h,42h
	defb	42h,42h,0A2h,71h,43h,0A1h,43h,73h
	defb	42h,42h,0FFh,0A1h,6Eh,82h,1Ch,66h
	defb	72h,39h,6Fh,82h,28h,6Eh,1Ch,66h
	defb	73h,3Bh,6Eh,82h,1Ch,6Fh,28h,66h
	defb	72h,39h,6Eh,82h,1Ch,66h,72h,39h
	defb	6Fh,82h,28h,6Eh,1Ch,66h,73h,3Bh
	defb	6Eh,82h,1Ch,6Fh,28h,66h,73h,3Bh
	defb	6Eh,82h,1Ch,66h,72h,37h,6Fh,82h
	defb	28h,6Eh,1Ch,66h,73h,39h,6Eh,82h
	defb	1Ch,6Fh,28h,66h,71h,32h,6Eh,82h
	defb	1Ch,66h,71h,32h,6Fh,82h,28h,6Eh
	defb	1Ch,66h,73h,34h,6Eh,82h,1Ch,6Fh
	defb	28h,66h,71h,32h,6Eh,82h,1Ch,66h
	defb	72h,39h,6Fh,82h,28h,6Eh,1Ch,66h
	defb	73h,3Bh,6Eh,82h,1Ch,6Fh,28h,66h
	defb	72h,39h,6Eh,82h,1Ch,66h,72h,39h
	defb	6Fh,82h,28h,6Eh,1Ch,66h,73h,3Bh
	defb	6Eh,82h,1Ch,6Fh,28h,66h,73h,3Bh
	defb	6Eh,82h,1Ch,66h,72h,37h,6Fh,82h
	defb	28h,6Eh,1Ch,66h,73h,39h,6Eh,82h
	defb	1Ch,6Fh,28h,66h,71h,32h,6Eh,82h
	defb	1Ch,66h,71h,32h,6Fh,82h,28h,6Eh
	defb	1Ch,66h,73h,34h,6Eh,82h,1Ch,6Fh
	defb	28h,66h,71h,32h,0FFh,0A1h,63h,74h
	defb	37h,0A2h,39h,0A5h,3Bh,0A1h,37h,0A2h
	defb	39h,0A3h,3Bh,0A2h,3Ch,0A1h,3Bh,0A2h
	defb	39h,0A5h,30h,0A1h,71h,3Eh,3Eh,3Eh
	defb	0A2h,73h,40h,0A1h,40h,71h,3Eh,3Eh
	defb	74h,37h,0A2h,39h,0A5h,3Bh,0A1h,37h
	defb	0A2h,39h,0A3h,3Bh,0A2h,3Ch,0A1h,3Bh
	defb	0A2h,39h,0A5h,30h,0A1h,71h,3Eh,3Eh
	defb	3Eh,0A2h,73h,40h,0A1h,40h,42h,42h
	defb	0FFh,0A1h,64h,79h,32h,39h,80h,0A5h
	defb	3Bh,0A1h,39h,39h,37h,32h,80h,37h
	defb	80h,34h,35h,80h,34h,80h,32h,30h
	defb	80h,0A2h,2Dh,66h,75h,40h,3Eh,0A1h
	defb	61h,78h,32h,34h,32h,64h,79h,32h
	defb	39h,80h,0A5h,3Bh,0A1h,39h,39h,37h
	defb	32h,80h,37h,80h,34h,35h,80h,34h
	defb	80h,37h,37h,80h,0A2h,36h,66h,75h
	defb	37h,39h,0A1h,61h,78h,32h,34h,36h
	defb	0FFh,0A1h,61h,75h,10h,1Ch,6Ah,10h
	defb	61h,10h,1Ch,10h,6Ah,10h,61h,1Ch
	defb	10h,1Ch,6Ah,10h,61h,10h,1Ch,10h
	defb	6Ah,10h,61h,1Ch,15h,21h,6Ah,15h
	defb	61h,15h,21h,15h,6Ah,15h,61h,21h
	defb	17h,23h,6Ah,17h,61h,17h,23h,17h
	defb	6Ah,17h,61h,23h,10h,1Ch,6Ah,10h
	defb	61h,10h,1Ch,10h,6Ah,10h,61h,1Ch
	defb	10h,1Ch,6Ah,10h,61h,10h,1Ch,10h
	defb	6Ah,10h,61h,1Ch,09h,15h,6Ah,09h
	defb	61h,09h,15h,09h,6Ah,09h,61h,15h
	defb	0Bh,17h,6Ah,0Bh,61h,0Bh,17h,0Bh
	defb	6Ah,0Bh,61h,17h,0FFh,0A1h,64h,7Dh
	defb	37h,37h,80h,0A5h,34h,0A1h,3Bh,3Bh
	defb	80h,0A5h,37h,0A1h,39h,80h,3Bh,39h
	defb	80h,37h,80h,0A2h,36h,66h,77h,3Fh
	defb	73h,3Fh,69h,7Fh,24h,0A1h,24h,64h
	defb	7Eh,34h,34h,80h,0A5h,2Fh,0A1h,37h
	defb	37h,80h,0A5h,34h,0A1h,36h,80h,37h
	defb	36h,80h,34h,80h,0A2h,36h,66h,73h
	defb	3Dh,3Fh,69h,7Fh,24h,0A1h,24h,0FFh
	defb	0A1h,6Eh,82h,1Ch,66h,72h,39h,6Fh
	defb	82h,28h,6Eh,1Ch,66h,7Bh,3Bh,6Eh
	defb	82h,1Ch,6Fh,28h,66h,72h,39h,6Eh
	defb	82h,1Ch,66h,72h,39h,6Fh,82h,28h
	defb	6Eh,1Ch,66h,7Bh,3Bh,6Eh,82h,1Ch
	defb	6Fh,28h,66h,7Bh,3Bh,6Eh,82h,1Ch
	defb	66h,7Ah,37h,6Fh,82h,28h,6Eh,1Ch
	defb	66h,7Ch,39h,6Eh,82h,1Ch,6Fh,28h
	defb	66h,73h,33h,6Eh,82h,1Ch,66h,73h
	defb	33h,6Fh,82h,28h,6Eh,1Ch,66h,77h
	defb	33h,6Eh,82h,1Ch,6Fh,28h,66h,73h
	defb	33h,6Eh,82h,1Ch,66h,72h,39h,6Fh
	defb	82h,28h,6Eh,1Ch,66h,7Bh,3Bh,6Eh
	defb	82h,1Ch,6Fh,28h,66h,72h,39h,6Eh
	defb	82h,1Ch,66h,72h,39h,6Fh,82h,28h
	defb	6Eh,1Ch,66h,7Bh,3Bh,6Eh,82h,1Ch
	defb	6Fh,28h,66h,7Bh,3Bh,6Eh,82h,1Ch
	defb	66h,7Ah,37h,6Fh,82h,28h,6Eh,1Ch
	defb	66h,7Ch,39h,6Eh,82h,1Ch,6Fh,28h
	defb	66h,73h,33h,6Eh,82h,1Ch,66h,73h
	defb	33h,6Fh,82h,28h,6Eh,1Ch,66h,77h
	defb	33h,6Eh,82h,1Ch,6Fh,28h,66h,73h
	defb	33h,0FFh,0A1h,64h,79h,32h,32h,30h
	defb	32h,80h,30h,80h,2Fh,2Bh,2Bh,28h
	defb	0A5h,26h,0A1h,26h,2Bh,80h,0A5h,2Dh
	defb	0A1h,37h,37h,34h,37h,80h,39h,80h
	defb	3Bh,37h,34h,32h,37h,80h,34h,80h
	defb	32h,2Dh,2Bh,26h,2Dh,80h,2Bh,80h
	defb	2Fh,0A3h,30h,32h,0A2h,34h,0A3h,37h
	defb	36h,0A2h

; Хвостовое заполнение нулями (0x0F2A..0x0F7F) до конца ROM.
data_padding_tail:
	defb	32h,0FFh,00h,00h,00h,00h,00h,00h
	defb	00h,00h,00h,00h,00h,00h,00h,00h
	defb	00h,00h,00h,00h,00h,00h,00h,00h
	defb	00h,00h,00h,00h,00h,00h,00h,00h
	defb	00h,00h,00h,00h,00h,00h,00h,00h
	defb	00h,00h,00h,00h,00h,00h,00h,00h
	defb	00h,00h,00h,00h,00h,00h,00h,00h
	defb	00h,00h,00h,00h,00h,00h,00h,00h
	defb	00h,00h,00h,00h,00h,00h,00h,00h
	defb	00h,00h,00h,00h,00h,00h,00h,00h
	defb	00h,00h,00h,00h,00h,00h

