; PUTUP_NEW.ROM - address-exact reconstruction of src/putup.rom
; GENERATED by tools/gen_layout.py -- do not hand-edit this file.
; org 0x0100; every exported object is placed at its ORIGINAL address;
; inter-object gaps (uncaptured code / RAM-var storage / Stage-11 music
; data without an asm file) are filled VERBATIM from src/putup.rom.

    org 0h
    include "var_ram_symbols.asm"

; --- emit func_entry @0x0100 (4 bytes) ---
    defs 0x0100 - $ ; align
    include "func_entry.asm"

; --- emit func_draw_tile_at_ptr @0x0104 (29 bytes) ---
    defs 0x0104 - $ ; align
    include "func_draw_tile_at_ptr.asm"

; --- emit func_sound_init @0x0121 (36 bytes) ---
    defs 0x0121 - $ ; align
    include "func_sound_init.asm"

; --- emit func_draw_char_at_hl @0x0145 (10 bytes) ---
    defs 0x0145 - $ ; align
    include "func_draw_char_at_hl.asm"

; --- emit func_set_text_ptr @0x014F (4 bytes) ---
    defs 0x014F - $ ; align
    include "func_set_text_ptr.asm"

; --- emit func_decode_key @0x0153 (25 bytes) ---
    defs 0x0153 - $ ; align
    include "func_decode_key.asm"

; --- emit data_keycode_table @0x016C (16 bytes) ---
    defs 0x016C - $ ; align
    include "data_keycode_table.asm"

; --- emit func_check_start_key @0x017C (27 bytes) ---
    defs 0x017C - $ ; align
    include "func_check_start_key.asm"

; --- emit func_read_keybuf @0x0197 (10 bytes) ---
    defs 0x0197 - $ ; align
    include "func_read_keybuf.asm"

; --- emit func_print_char_at_ptr @0x01A1 (13 bytes) ---
    defs 0x01A1 - $ ; align
    include "func_print_char_at_ptr.asm"

; --- emit func_restore_cursor @0x01AE (14 bytes) ---
    defs 0x01AE - $ ; align
    include "func_restore_cursor.asm"

; --- emit func_sound_op @0x01BC (17 bytes) ---
    defs 0x01BC - $ ; align
    include "func_sound_op.asm"

; --- emit data_snd_dispatch_table @0x01CD (32 bytes) ---
    defs 0x01CD - $ ; align
    include "data_snd_dispatch_table.asm"

; --- gap 0x01ED..0x0201 (20 bytes) from original image ---
    defs 0x01ED - $ ; align
    INCBIN "bin/gap_01ED_0201.bin"

; --- emit func_snd_out_ch0 @0x0201 (13 bytes) ---
    defs 0x0201 - $ ; align
    include "func_snd_out_ch0.asm"

; --- emit func_snd_calc_period @0x020E (11 bytes) ---
    defs 0x020E - $ ; align
    include "func_snd_calc_period.asm"

; --- gap 0x0219..0x022D (20 bytes) from original image ---
    defs 0x0219 - $ ; align
    INCBIN "bin/gap_0219_022D.bin"

; --- emit func_snd_out_ch1 @0x022D (13 bytes) ---
    defs 0x022D - $ ; align
    include "func_snd_out_ch1.asm"

; --- gap 0x023A..0x024E (20 bytes) from original image ---
    defs 0x023A - $ ; align
    INCBIN "bin/gap_023A_024E.bin"

; --- emit func_snd_out_ch2 @0x024E (13 bytes) ---
    defs 0x024E - $ ; align
    include "func_snd_out_ch2.asm"

; --- gap 0x025B..0x026E (19 bytes) from original image ---
    defs 0x025B - $ ; align
    INCBIN "bin/gap_025B_026E.bin"

; --- emit func_snd_toggle @0x026E (18 bytes) ---
    defs 0x026E - $ ; align
    include "func_snd_toggle.asm"

; --- emit data_snd_toggle_table @0x0280 (16 bytes) ---
    defs 0x0280 - $ ; align
    include "data_snd_toggle_table.asm"

; --- emit func_snd_enable_ch0 @0x0290 (14 bytes) ---
    defs 0x0290 - $ ; align
    include "func_snd_enable_ch0.asm"

; --- emit func_snd_enable_ch1 @0x029E (14 bytes) ---
    defs 0x029E - $ ; align
    include "func_snd_enable_ch1.asm"

; --- emit func_snd_enable_ch2 @0x02AC (14 bytes) ---
    defs 0x02AC - $ ; align
    include "func_snd_enable_ch2.asm"

; --- emit func_snd_enable_ch01 @0x02BA (6 bytes) ---
    defs 0x02BA - $ ; align
    include "func_snd_enable_ch01.asm"

; --- emit func_snd_enable_ch02 @0x02C0 (6 bytes) ---
    defs 0x02C0 - $ ; align
    include "func_snd_enable_ch02.asm"

; --- emit func_snd_enable_ch12 @0x02C6 (6 bytes) ---
    defs 0x02C6 - $ ; align
    include "func_snd_enable_ch12.asm"

; --- emit func_snd_enable_ch012 @0x02CC (6 bytes) ---
    defs 0x02CC - $ ; align
    include "func_snd_enable_ch012.asm"

; --- emit func_snd_gate_ch0 @0x02D2 (24 bytes) ---
    defs 0x02D2 - $ ; align
    include "func_snd_gate_ch0.asm"

; --- emit func_snd_gate_ch1 @0x02EA (24 bytes) ---
    defs 0x02EA - $ ; align
    include "func_snd_gate_ch1.asm"

; --- emit func_snd_gate_ch2 @0x0302 (24 bytes) ---
    defs 0x0302 - $ ; align
    include "func_snd_gate_ch2.asm"

; --- gap 0x031A..0x0321 (7 bytes) from original image ---
    defs 0x031A - $ ; align
    INCBIN "bin/gap_031A_0321.bin"

; --- emit func_print_string @0x0321 (11 bytes) ---
    defs 0x0321 - $ ; align
    include "func_print_string.asm"

; --- emit func_hl_add_a @0x032C (5 bytes) ---
    defs 0x032C - $ ; align
    include "func_hl_add_a.asm"

; --- emit func_print_uint16 @0x0331 (36 bytes) ---
    defs 0x0331 - $ ; align
    include "func_print_uint16.asm"

; --- emit func_divmod_u16 @0x0355 (15 bytes) ---
    defs 0x0355 - $ ; align
    include "func_divmod_u16.asm"

; --- gap 0x0364..0x0383 (31 bytes) from original image ---
    defs 0x0364 - $ ; align
    INCBIN "bin/gap_0364_0383.bin"

; --- emit func_hw_init @0x0383 (33 bytes) ---
    defs 0x0383 - $ ; align
    include "func_hw_init.asm"

; --- emit func_vblank_isr @0x03A4 (93 bytes) ---
    defs 0x03A4 - $ ; align
    include "func_vblank_isr.asm"

; --- emit func_load_glyph_block @0x0401 (56 bytes) ---
    defs 0x0401 - $ ; align
    include "func_load_glyph_block.asm"

; --- emit func_blit_plane_mask80 @0x0439 (37 bytes) ---
    defs 0x0439 - $ ; align
    include "func_blit_plane_mask80.asm"

; --- emit func_blit_plane_mask40 @0x045E (37 bytes) ---
    defs 0x045E - $ ; align
    include "func_blit_plane_mask40.asm"

; --- emit func_blit_plane_mask20 @0x0483 (37 bytes) ---
    defs 0x0483 - $ ; align
    include "func_blit_plane_mask20.asm"

; --- emit func_blit_plane_mask10 @0x04A8 (37 bytes) ---
    defs 0x04A8 - $ ; align
    include "func_blit_plane_mask10.asm"

; --- emit func_load_gfx_2761 @0x04CD (78 bytes) ---
    defs 0x04CD - $ ; align
    include "func_load_gfx_2761.asm"

; --- emit data_vram_col_table @0x051B (32 bytes) ---
    defs 0x051B - $ ; align
    include "data_vram_col_table.asm"

; --- gap 0x053B..0x0600 (197 bytes) from original image ---
    defs 0x053B - $ ; align
    INCBIN "bin/gap_053B_0600.bin"

; --- emit data_glyph_ptr_table @0x0600 (512 bytes) ---
    defs 0x0600 - $ ; align
    include "data_glyph_ptr_table.asm"

; --- emit func_put_char @0x0800 (3 bytes) ---
    defs 0x0800 - $ ; align
    include "func_put_char.asm"

; --- emit func_render_glyph @0x0803 (192 bytes) ---
    defs 0x0803 - $ ; align
    include "func_render_glyph.asm"

; --- gap 0x08C3..0x0925 (98 bytes) from original image ---
    defs 0x08C3 - $ ; align
    INCBIN "bin/gap_08C3_0925.bin"

; --- emit str_credits_koi8 @0x0925 (126 bytes) ---
    defs 0x0925 - $ ; align
    include "str_credits_koi8.asm"

; --- gap 0x09A3..0x0A06 (99 bytes) from original image ---
    defs 0x09A3 - $ ; align
    INCBIN "bin/gap_09A3_0A06.bin"

; --- emit str_title_logo @0x0A06 (193 bytes) ---
    defs 0x0A06 - $ ; align
    include "str_title_logo.asm"

; --- emit str_push_space @0x0AC7 (15 bytes) ---
    defs 0x0AC7 - $ ; align
    include "str_push_space.asm"

; --- emit str_msx_magazine @0x0AD6 (19 bytes) ---
    defs 0x0AD6 - $ ; align
    include "str_msx_magazine.asm"

; --- emit str_hi @0x0AE9 (4 bytes) ---
    defs 0x0AE9 - $ ; align
    include "str_hi.asm"

; --- emit str_score @0x0AED (7 bytes) ---
    defs 0x0AED - $ ; align
    include "str_score.asm"

; --- emit str_round @0x0AF4 (7 bytes) ---
    defs 0x0AF4 - $ ; align
    include "str_round.asm"

; --- emit str_time @0x0AFB (6 bytes) ---
    defs 0x0AFB - $ ; align
    include "str_time.asm"

; --- emit str_hurry_up @0x0B01 (13 bytes) ---
    defs 0x0B01 - $ ; align
    include "str_hurry_up.asm"

; --- emit str_game_over @0x0B0E (10 bytes) ---
    defs 0x0B0E - $ ; align
    include "str_game_over.asm"

; --- emit str_congratulation @0x0B18 (17 bytes) ---
    defs 0x0B18 - $ ; align
    include "str_congratulation.asm"

; --- emit str_bonus @0x0B29 (19 bytes) ---
    defs 0x0B29 - $ ; align
    include "str_bonus.asm"

; --- gap 0x0B3C..0x0B57 (27 bytes) from original image ---
    defs 0x0B3C - $ ; align
    INCBIN "bin/gap_0B3C_0B57.bin"

; --- emit func_main_init @0x0B57 (270 bytes) ---
    defs 0x0B57 - $ ; align
    include "func_main_init.asm"

; --- emit lbl_title_key_poll @0x0C65 (62 bytes) ---
    defs 0x0C65 - $ ; align
    include "lbl_title_key_poll.asm"

; --- emit func_erase_char_08E9 @0x0CA3 (61 bytes) ---
    defs 0x0CA3 - $ ; align
    include "func_erase_char_08E9.asm"

; --- emit func_game_update @0x0CE0 (421 bytes) ---
    defs 0x0CE0 - $ ; align
    include "func_game_update.asm"

; --- emit lbl_main_game_loop @0x0E85 (114 bytes) ---
    defs 0x0E85 - $ ; align
    include "lbl_main_game_loop.asm"

; --- emit func_delay @0x0EF7 (18 bytes) ---
    defs 0x0EF7 - $ ; align
    include "func_delay.asm"

; --- emit func_score_and_redraw @0x0F09 (48 bytes) ---
    defs 0x0F09 - $ ; align
    include "func_score_and_redraw.asm"

; --- gap 0x0F39..0x1123 (490 bytes) from original image ---
    defs 0x0F39 - $ ; align
    INCBIN "bin/gap_0F39_1123.bin"

; --- emit func_prng @0x1123 (50 bytes) ---
    defs 0x1123 - $ ; align
    include "func_prng.asm"

; --- gap 0x1155..0x1197 (66 bytes) from original image ---
    defs 0x1155 - $ ; align
    INCBIN "bin/gap_1155_1197.bin"

; --- emit func_draw_score_hud @0x1197 (82 bytes) ---
    defs 0x1197 - $ ; align
    include "func_draw_score_hud.asm"

; --- emit func_play_sfx @0x11E9 (5 bytes) ---
    defs 0x11E9 - $ ; align
    include "func_play_sfx.asm"

; --- emit func_draw_level_hud @0x11EE (44 bytes) ---
    defs 0x11EE - $ ; align
    include "func_draw_level_hud.asm"

; --- emit func_draw_status_hud @0x121A (56 bytes) ---
    defs 0x121A - $ ; align
    include "func_draw_status_hud.asm"

; --- gap 0x1252..0x130A (184 bytes) from original image ---
    defs 0x1252 - $ ; align
    INCBIN "bin/gap_1252_130A.bin"

; --- emit func_draw_game_objects @0x130A (160 bytes) ---
    defs 0x130A - $ ; align
    include "func_draw_game_objects.asm"

; --- gap 0x13AA..0x1477 (205 bytes) from original image ---
    defs 0x13AA - $ ; align
    INCBIN "bin/gap_13AA_1477.bin"

; --- emit func_delay_long @0x1477 (18 bytes) ---
    defs 0x1477 - $ ; align
    include "func_delay_long.asm"

; --- emit func_entity_state1 @0x1489 (112 bytes) ---
    defs 0x1489 - $ ; align
    include "func_entity_state1.asm"

; --- emit func_entity_state2 @0x14F9 (111 bytes) ---
    defs 0x14F9 - $ ; align
    include "func_entity_state2.asm"

; --- emit func_entity_state3 @0x1568 (119 bytes) ---
    defs 0x1568 - $ ; align
    include "func_entity_state3.asm"

; --- emit func_entity_state4 @0x15DF (112 bytes) ---
    defs 0x15DF - $ ; align
    include "func_entity_state4.asm"

; --- emit func_entity_state5 @0x164F (173 bytes) ---
    defs 0x164F - $ ; align
    include "func_entity_state5.asm"

; --- emit func_entity_state6 @0x16FC (172 bytes) ---
    defs 0x16FC - $ ; align
    include "func_entity_state6.asm"

; --- emit func_entity_state7 @0x17A8 (169 bytes) ---
    defs 0x17A8 - $ ; align
    include "func_entity_state7.asm"

; --- emit func_entity_state8 @0x1851 (173 bytes) ---
    defs 0x1851 - $ ; align
    include "func_entity_state8.asm"

; --- emit func_entity_state9 @0x18FE (29 bytes) ---
    defs 0x18FE - $ ; align
    include "func_entity_state9.asm"

; --- emit func_entity_state10 @0x191B (97 bytes) ---
    defs 0x191B - $ ; align
    include "func_entity_state10.asm"

; --- emit func_level_loader @0x197C (523 bytes) ---
    defs 0x197C - $ ; align
    include "func_level_loader.asm"

; --- emit func_draw_tile_to_buf @0x1B87 (33 bytes) ---
    defs 0x1B87 - $ ; align
    include "func_draw_tile_to_buf.asm"

; --- emit func_render_tile_vram @0x1BA8 (33 bytes) ---
    defs 0x1BA8 - $ ; align
    include "func_render_tile_vram.asm"

; --- emit func_memcpy @0x1BC9 (11 bytes) ---
    defs 0x1BC9 - $ ; align
    include "func_memcpy.asm"

; --- emit func_coords_to_textbuf @0x1BD4 (17 bytes) ---
    defs 0x1BD4 - $ ; align
    include "func_coords_to_textbuf.asm"

; --- emit func_clear_textbuf @0x1BE5 (21 bytes) ---
    defs 0x1BE5 - $ ; align
    include "func_clear_textbuf.asm"

; --- gap 0x1BFA..0x1C0E (20 bytes) from original image ---
    defs 0x1BFA - $ ; align
    INCBIN "bin/gap_1BFA_1C0E.bin"

; --- emit data_level_params @0x1C0E (128 bytes) ---
    defs 0x1C0E - $ ; align
    include "data_level_params.asm"

; --- emit data_level_maps @0x1C8E (2640 bytes) ---
    defs 0x1C8E - $ ; align
    include "data_level_maps.asm"

; --- emit data_tile_table_26DE @0x26DE (40 bytes) ---
    defs 0x26DE - $ ; align
    include "data_tile_table_26DE.asm"

; --- emit data_tile_graphics @0x2706 (91 bytes) ---
    defs 0x2706 - $ ; align
    include "data_tile_graphics.asm"

; --- emit data_gfx_2761 @0x2761 (2048 bytes) ---
    defs 0x2761 - $ ; align
    include "data_gfx_2761.asm"

; --- emit data_sprites_2F61 @0x2F61 (224 bytes) ---
    defs 0x2F61 - $ ; align
    include "data_sprites_2F61.asm"

; --- emit data_packed_font_3041 @0x3041 (2041 bytes) ---
    defs 0x3041 - $ ; align
    include "data_packed_font_3041.asm"

; --- gap 0x383A..0x3858 (30 bytes) from original image ---
    defs 0x383A - $ ; align
    INCBIN "bin/gap_383A_3858.bin"

; --- emit func_music_tick @0x3858 (52 bytes) ---
    defs 0x3858 - $ ; align
    include "func_music_tick.asm"

; --- gap 0x388C..0x3902 (118 bytes) from original image ---
    defs 0x388C - $ ; align
    INCBIN "bin/gap_388C_3902.bin"

; --- emit func_music_load_voice_params @0x3902 (62 bytes) ---
    defs 0x3902 - $ ; align
    include "func_music_load_voice_params.asm"

; --- emit func_snd_op_keep_a @0x3940 (6 bytes) ---
    defs 0x3940 - $ ; align
    include "func_snd_op_keep_a.asm"

; --- emit func_music_process_voice @0x3946 (457 bytes) ---
    defs 0x3946 - $ ; align
    include "func_music_process_voice.asm"

; --- emit func_music_set_note_params @0x3B0F (185 bytes) ---
    defs 0x3B0F - $ ; align
    include "func_music_set_note_params.asm"

; --- gap 0x3BC8..0x3BCA (2 bytes) from original image ---
    defs 0x3BC8 - $ ; align
    INCBIN "bin/gap_3BC8_3BCA.bin"

; --- emit func_music_play_note_ch0 @0x3BCA (173 bytes) ---
    defs 0x3BCA - $ ; align
    include "func_music_play_note_ch0.asm"

; --- emit func_snd_op_keep_a2 @0x3C77 (6 bytes) ---
    defs 0x3C77 - $ ; align
    include "func_snd_op_keep_a2.asm"

; --- emit func_music_play_note_ch1 @0x3C7D (203 bytes) ---
    defs 0x3C7D - $ ; align
    include "func_music_play_note_ch1.asm"

; --- emit func_snd_op_keep_a3 @0x3D48 (6 bytes) ---
    defs 0x3D48 - $ ; align
    include "func_snd_op_keep_a3.asm"

; --- emit func_music_init @0x3D4E (106 bytes) ---
    defs 0x3D4E - $ ; align
    include "func_music_init.asm"

; --- emit func_memcpy_keep_psw @0x3DB8 (13 bytes) ---
    defs 0x3DB8 - $ ; align
    include "func_memcpy_keep_psw.asm"

; --- gap 0x3DC5..0x3DCD (8 bytes) from original image ---
    defs 0x3DC5 - $ ; align
    INCBIN "bin/gap_3DC5_3DCD.bin"

; --- emit func_music_start_track @0x3DCD (27 bytes) ---
    defs 0x3DCD - $ ; align
    include "func_music_start_track.asm"

; --- emit data_music_track_setup @0x3DE8 (3 bytes) ---
    defs 0x3DE8 - $ ; align
    include "data_music_track_setup.asm"

; --- gap 0x3DEB..0x42F9 (1294 bytes) from original image ---
    defs 0x3DEB - $ ; align
    INCBIN "bin/gap_3DEB_42F9.bin"

; --- emit data_note_table_ch1 @0x42F9 (256 bytes) ---
    defs 0x42F9 - $ ; align
    include "data_note_table_ch1.asm"

; --- emit data_note_param_table_43F9 @0x43F9 (99 bytes) ---
    defs 0x43F9 - $ ; align
    include "data_note_param_table_43F9.asm"

; --- gap 0x445C..0x445D (1 bytes) from original image ---
    defs 0x445C - $ ; align
    INCBIN "bin/gap_445C_445D.bin"

; --- emit data_note_freq_table_ch0 @0x445D (419 bytes) ---
    defs 0x445D - $ ; align
    include "data_note_freq_table_ch0.asm"

; image end @0x4600
