; Code section — generated by v06c-asm-export
; View only: the build consumes layout.asm (Stage 6.23 §2.2)
; Control-flow analysis, clipped to the ROM window (§2.1)


; --- Code range: 0100 ---
; Точка входа ROM: JMP 0x04CF (инициализация). Самомодифицируется в JMP 0x049D (главный цикл) через SHLD 0101 в func_patch_entry_jump.
func_rom_entry:
	jmp	func_init_song

; --- Code range: 0105 ---
; Поиск по таблице: CMP M / RZ / DAD B / JMP 0x0105 — продвигает HL на шаг BC пока [HL]!=A; возврат RZ при совпадении.
func_search_value:
	cmp	m
	rz
	dad	b
	jmp	func_search_value
; Читает 16-битное слово из [HL] в DE (little-endian), HL+=2. MOV E,M; INX H; MOV D,M; INX H; XCHG; RET.
func_read_word_de:
	mov	e,m
	inx	h
	mov	d,m
	inx	h
	xchg
; HL += самоизменяемая база (операнд 0x0111, пишется SHLD 0111 в func_init_song), затем DAD B; DE=HL. Вычисление базового адреса таблицы.
func_add_selfmod_base:
	lxi	b,082ah
	dad	b
	xchg
	ret
; Декодирование события паттерна: индекс A*3 от базы [0x0103], 6-байтные записи, тест бита 7, возврат флагов/значений.
func_event_decode:
	mvi	d,00h
	mov	e,a
	add	a
	add	e
	mov	e,a
	lhld	var_cur_stream_ptr
	dad	d
	shld	var_cur_stream_ptr
	inx	h
	mov	a,m
	push	psw
	rlc
	mvi	c,10h
	jc	label_012D
	mov	c,d
label_012D:
	rlc
	mvi	b,02h
	jc	label_0134
	mov	b,d
label_0134:
	pop	psw
	inx	h
	mov	e,m
	dcx	h
	push	h
	dcx	h
	ani	1fh
	mov	d,a
	mov	a,m
	mov	h,d
	push	psw
	ani	0f0h
	rrc
	rrc
	rrc
	rrc
	mov	d,a
	pop	psw
	ani	0fh
	mov	l,a
	xthl
	mvi	a,20h
	ana	m
	pop	h
	mov	a,l
	rz
	mvi	a,10h
	ora	d
	mov	d,a
	mov	a,l
	ret
; Загрузка/переход по паттерну: индекс var_048E, сравнение с var_song_length, чтение таблиц 0x045E/0x0462, запись указателей потока 0x0469/0x046B/0x046D. Вызывается по условию (CZ 0x0158) из func_player_tick.
func_pattern_fetch:
	lda	048eh
	mov	c,a
	lxi	h,0468h
	cmp	m
	jc	label_0165
	xra	a
	mov	c,a
label_0165:
	inr	a
	sta	048eh
	mov	l,c
	mvi	h,00h
	dad	h
	xchg
	lhld	var_pattern_base_A
	xchg
	dad	d
	mov	c,m
	inx	h
	mov	a,m
	sta	041eh
	mov	a,c
	lhld	var_pattern_base_C
	lxi	b,0007h
	call	func_search_value
	inx	h
	call	func_read_word_de
	push	h
	lxi	h,0469h
	mov	m,e
	inx	h
	mov	m,d
	inx	h
	xthl
	call	func_read_word_de
	xthl
	mov	m,e
	inx	h
	mov	m,d
	inx	h
	xthl
	call	func_read_word_de
	xthl
	mov	m,e
	inx	h
	mov	m,d
	pop	h
	ret
; Dispatch дешифровки трюка: CALL 0x055F (адрес слота), затем B=12, HL=ключ 0x0553, PUSH D, JMP 0x056A (XOR-цикл).
func_thunk_decrypt_dispatch:
	call	func_thunk_slot_addr
	mvi	b,0ch
	lxi	h,0553h
	push	d
	jmp	func_xor_decrypt_loop
; Тик проигрывателя: делитель темпа (LDA/DCR/STA 0x0467, JNZ 0x033A), перезагрузка из 0x0466; для 3 каналов SHLD 0x0103 (базы 0x0472/0x047C/0x0486), CALL thunk_decrypt_dispatch, CALL command_dispatch, SHLD потока.
func_player_tick:
	lda	var_tempo_counter
	dcr	a
	sta	var_tempo_counter
	jnz	func_channels_process
	lda	var_tempo
	sta	var_tempo_counter
	lxi	h,0472h
	shld	var_cur_stream_ptr
	call	func_thunk_decrypt_dispatch
	jp	label_01DB
	lhld	var_stream_ptr_A
	mov	a,m
	inr	a
	cz	func_pattern_fetch
	lhld	var_stream_ptr_A
	call	func_command_dispatch
	shld	var_stream_ptr_A
label_01DB:
	lxi	h,047ch
	shld	var_cur_stream_ptr
	call	func_thunk_decrypt_dispatch
	jp	label_01F0
	lhld	var_stream_ptr_B
	call	func_command_dispatch
	shld	var_stream_ptr_B
label_01F0:
	lxi	h,0486h
	shld	var_cur_stream_ptr
	call	func_thunk_decrypt_dispatch
	jp	func_channels_process
	lhld	var_stream_ptr_C
	call	func_command_dispatch
	shld	var_stream_ptr_C
	jmp	func_channels_process
; Интерпретатор команд нотного потока: A=[M]; CPI 60/70/80/81/82/8F — диспетчер на обработчики 0x023C/0x024D/0x027F/0x026B/0x024B/0x02A1/0x027B.
func_command_dispatch:
	mov	a,m
	cpi	60h
	jc	func_cmd_handler_60
	cpi	70h
	jc	func_cmd_note_pitch
	cpi	80h
	jc	func_cmd_sui70
	jz	func_cmd_rest
	cpi	81h
	jz	func_cmd_retn_inx
	cpi	82h
	jz	func_cmd_zero
	cpi	8fh
	jc	func_cmd_80
	sui	0a1h
	push	h
	lhld	var_cur_stream_ptr
	inx	h
	inx	h
	mov	m,a
	dcx	h
	dcx	h
	dcx	h
	mov	m,a
	pop	h
	inx	h
	jmp	func_command_dispatch
; Обработчик команд <0x60: запись значения в поток по [0x0103] (+6), установка поля =0x20, возврат в диспетчер (JMP 0x0208).
func_cmd_handler_60:
	push	h
	lhld	var_cur_stream_ptr
	mvi	m,00h
	inx	h
	mov	m,a
	lxi	b,0006h
	dad	b
	mvi	m,20h
	pop	h
; INX H; RET — общий выход/шаг обработчика команды 0x81.
func_cmd_retn_inx:
	inx	h
	ret
; Команда ноты 0x60-0x6F: SUI 0x60, поиск по pitch-таблице канала (LHLD 0x0464; CALL 0x0105, шаг 0x63), запись тона в поток ([0x0103]+3).
func_cmd_note_pitch:
	sui	60h
	push	h
	lxi	b,0063h
	lhld	var_pitch_table_base
	call	func_search_value
	inx	h
	push	h
	lhld	var_cur_stream_ptr
	lxi	b,0003h
	dad	b
	pop	b
	mov	m,c
	inx	h
	mov	m,b
	pop	h
	inx	h
	jmp	func_command_dispatch
; Команда пауза (0x80): установка [0x0103+7]=0xFF (рест), сдвиг указателя потока.
func_cmd_rest:
	inx	h
label_026C:
	push	h
	lhld	var_cur_stream_ptr
	inx	h
	inx	h
	inx	h
	inx	h
	inx	h
	inx	h
	inx	h
	mvi	m,0ffh
	pop	h
	ret
; Обработчик команды 0x82: XRA A; JMP 0x0281 (вставка нулевого значения в поток через note_lookup).
func_cmd_zero:
	xra	a
	jmp	func_note_lookup
; Команда 0x70-0x7F: SUI 0x70 (код), далее общий путь note_lookup.
func_cmd_sui70:
	sui	70h
; Поиск ноты/длительности: LXI B,0x21; LHLD 0x0460; CALL 0x0105 — поиск по таблице, запись слова в поток ([0x0103]-2). Общий хвост 0x0294.
func_note_lookup:
	push	h
	lxi	b,0021h
	lhld	var_pattern_base_B
	call	func_search_value
	inx	h
	push	h
	lhld	var_cur_stream_ptr
	dcx	h
	dcx	h
	mvi	m,00h
label_0294:
	lxi	b,0007h
	dad	b
	pop	b
	mov	m,c
	inx	h
	mov	m,b
	pop	h
	inx	h
	jmp	func_command_dispatch
; Команда 0x80-0x8E (смена параметров): STA 0x049C/0x049A, пометка потока [0x0103-2]=1, поиск ноты (LHLD 0x0460; CALL 0x0105), JMP 0x0294.
func_cmd_80:
	sui	80h
	sta	var_ay_note_reg
	inx	h
	mov	a,m
	sta	049ah
	push	h
	lhld	var_cur_stream_ptr
	dcx	h
	dcx	h
	mvi	m,01h
	push	h
	xra	a
	lxi	b,0021h
	lhld	var_pattern_base_B
	call	func_search_value
	inx	h
	xthl
	jmp	label_0294
; Декодирование длительности/удержания ноты: чтение [0x0103+7], ANI 0x1F, обращение к таблице 0x0060 (смещение из потока), корректировка счётчика удержания и указателя.
func_duration_decode:
	lhld	var_cur_stream_ptr
	lxi	d,0007h
	dad	d
	mov	a,m
	inr	a
	rz
	dcr	a
	dcr	a
	mov	m,a
	push	psw
	lhld	var_cur_stream_ptr
	mov	a,m
	mov	c,a
	inr	a
	ani	1fh
	mov	m,a
	pop	psw
	rnz
	inx	h
	inx	h
	inx	h
	mov	e,m
	inx	h
	mov	d,m
	lxi	h,0060h
	dad	d
	mov	a,m
	dcr	a
	jm	label_026C
	mov	c,a
	inx	h
	mov	a,m
	inr	a
	push	d
	push	h
	lhld	var_cur_stream_ptr
	mov	e,a
	mov	a,c
	inr	a
	ani	1fh
	mov	m,a
	mov	a,e
	lxi	d,0007h
	dad	d
	mov	m,a
	pop	h
	pop	d
	ret
; Сохранение громкости: если C==0 — STA 0x0495 (значение из H).
func_vol_store:
	mov	a,c
	ora	a
	rnz
	mov	a,h
	sta	0495h
	ret
; Проверка/установка гейта канала: чтение [0x0103+7], флаги по [0x0103-2], запись режима 0x02/0 в 0x049C.
func_channel_gate:
	push	h
	lhld	var_cur_stream_ptr
	push	b
	lxi	b,0007h
	dad	b
	pop	b
	mov	a,m
	inr	a
label_0317:
	pop	h
	rz
	push	h
	lhld	var_cur_stream_ptr
	dcx	h
	dcx	h
	mov	a,m
	ora	a
	jz	label_0317
	cpi	02h
	jz	label_032E
	mvi	m,02h
	jmp	label_0332
label_032E:
	xra	a
	sta	var_ay_note_reg
label_0332:
	pop	h
	push	psw
	mvi	a,10h
	ora	m
	mov	m,a
	pop	psw
	ret
; Обработка 3 каналов (хвост func_player_tick): для каждого канала SHLD 0x0103 (0x0472/0x047C/0x0486), CALL duration_decode/pattern/event_decode/pitch_calc/vol_store/channel_gate, накопление значений AY-регистров в 0x0496/0x0497/0x0498/0x0499; в конце JMP 0x0442 (вывод в AY).
func_channels_process:
	lxi	h,0472h
	push	h
	shld	var_cur_stream_ptr
	call	func_duration_decode
	mov	a,c
	sta	0419h
	lhld	0475h
	shld	var_cur_stream_ptr
	call	func_event_decode
	mov	a,c
	ora	b
	rrc
	sta	0496h
	xthl
	shld	var_cur_stream_ptr
	push	b
	lxi	b,0007h
	dad	b
	pop	b
	mov	a,m
	pop	h
	inr	a
	jz	label_0370
	call	func_vol_store
	call	func_pitch_calc
	shld	048fh
label_0370:
	lxi	h,0497h
	mov	m,a
	call	func_channel_gate
	lxi	h,047ch
	push	h
	shld	var_cur_stream_ptr
	call	func_duration_decode
	xthl
	push	b
	lxi	b,0007h
	dad	b
	pop	b
	mov	a,m
	pop	h
	inr	a
	jz	label_03B4
	mov	a,c
	sta	0419h
	lhld	047fh
	shld	var_cur_stream_ptr
	call	func_event_decode
	lda	0496h
	ora	c
	ora	b
	sta	0496h
	call	func_vol_store
	push	h
	lxi	h,047ch
	shld	var_cur_stream_ptr
	pop	h
	call	func_pitch_calc
	shld	0491h
label_03B4:
	lxi	h,0498h
	mov	m,a
	call	func_channel_gate
	lxi	h,0486h
	push	h
	shld	var_cur_stream_ptr
	call	func_duration_decode
	xthl
	push	b
	lxi	b,0007h
	dad	b
	pop	b
	mov	a,m
	pop	h
	inr	a
	jz	label_03FE
	mov	a,c
	sta	0419h
	lhld	0489h
	shld	var_cur_stream_ptr
	call	func_event_decode
	mov	a,c
	rlc
	mov	c,a
	mov	a,b
	rlc
	mov	b,a
	lda	0496h
	ora	b
	ora	c
	sta	0496h
	call	func_vol_store
	push	h
	lxi	h,0486h
	shld	var_cur_stream_ptr
	pop	h
	call	func_pitch_calc
	shld	0493h
label_03FE:
	lxi	h,0499h
	mov	m,a
	call	func_channel_gate
	jmp	func_ay_write_registers
; Расчёт периода тона: индекс*2 (ADI/ADD A), обращение к master pitch table 0x057A (DAD), чтение 16-бит, маскирование 0xEF (шум/мост), сложение с базой потока. Возврат периода в HL.
func_pitch_calc:
	mov	a,l
	push	psw
	push	d
	lhld	var_cur_stream_ptr
	inx	h
	mov	a,m
	lxi	d,0004h
	dad	d
	mov	e,m
	inx	h
	mov	d,m
	xchg
	lxi	d,0003h
	dad	d
	add	m
	adi	00h
	add	a
	mov	e,a
	mvi	d,00h
	lxi	h,057ah
	dad	d
	mov	e,m
	inx	h
	mov	d,m
	xchg
	pop	d
	mvi	a,0efh
	ana	d
	cmp	d
	mov	d,a
	jz	label_0437
	pop	psw
	dad	d
	ret
label_0437:
	mov	a,d
	cma
	mov	d,a
	mov	a,e
	cma
	mov	e,a
	inx	h
	pop	psw
	ana	a
	dad	d
	ret
; Вывод в AY-3-8910: обход таблицы регистров от 0x049C вниз; OUT 0x15 (номер регистра) + OUT 0x14 (значение); регистры 0x0A..0x00 (тон A/B/C, noise, mixer, volume). Проверено по I/O-трассе.
func_ay_write_registers:
	lxi	h,049ch
	xra	a
	ora	m
	mvi	a,0dh
	jnz	label_0451
	sui	03h
	dcx	h
	dcx	h
	dcx	h
label_0451:
	out	15h
	mov	b,a
	mov	a,m
	out	14h
	dcx	h
	mov	a,b
	dcr	a
	jp	label_0451
	ret

; --- Code range: 049D ---
; Главный цикл: DI; CALL func_player_tick; программная задержка (LXI H,0x0BFC; DCR L/H; JNZ); IN 0x01 (всегда 0xEF) + RAL/JC; ветка счётчика 0x04BB (переменная 0x04A2 вписана в код LXI H); JMP 0x049D.
func_main_loop:
	di
	call	func_player_tick
	lxi	h,0bfch
label_04A4:
	dcr	l
	jnz	label_04A4
	dcr	h
	jnz	label_04A4
	in	01h
	ral
	jc	label_04BB
	mvi	a,07h
	out	15h
	dcr	l
	mov	a,l
	out	14h
	ret
label_04BB:
	lhld	04a2h
	dcx	h
	ral
	jnc	label_04C9
	ral
	jc	func_main_loop
	inx	h
	inx	h
label_04C9:
	shld	04a2h
	jmp	func_main_loop
; Инициализация трека: DI; разбор заголовка 0x0657 (темп->0x0466, длина->0x0468, базы каналов->0x045E/0x0460/0x0462, база питча->0x0464); очистка таблицы состояния 0x046F..0x049B (45 байт, 1-й байт 0xFF); инициализация 3 каналов; JMP func_patch_entry_jump.
func_init_song:
	di
	lxi	h,0657h
	mov	a,m
	sta	var_tempo
	shld	0111h
	inx	h
	call	func_read_word_de
	ldax	d
	inx	d
	inr	a
	sta	var_song_length
	lxi	b,045eh
	call	func_store_de_to_bc
	call	func_read_word_de
	lxi	b,0460h
	call	func_store_de_to_bc
	push	d
	call	func_read_word_de
	lxi	b,0462h
	call	func_store_de_to_bc
	lxi	h,001bh
	call	func_add_selfmod_base
	xchg
	shld	var_pitch_table_base
	lxi	h,046fh
	shld	var_stream_ptr_A
	mvi	m,0ffh
	inx	h
	mvi	b,2dh
label_0512:
	mvi	m,00h
	inx	h
	dcr	b
	jnz	label_0512
	pop	h
	lxi	b,0021h
	xra	a
	call	func_search_value
	dcr	a
	sta	0479h
	sta	0483h
	sta	048dh
	mvi	a,01h
	sta	var_tempo_counter
	inx	h
	shld	0477h
	shld	0481h
	shld	048bh
	jmp	func_patch_entry_jump
; EI; RET — короткий хвост (разрешить прерывания и вернуться). Статических xref нет; объект создан для 100% покрытия (разрыв между func_init_song и func_store_de_to_bc).
func_053D_ei_ret:
	ei
	ret
; Сохранить 16-бит DE в [BC] и [BC+1] с сохранением регистров (PUSH B/PSW; STAX; INX B; STAX; POP).
func_store_de_to_bc:
	push	b
	push	psw
	mov	a,e
	stax	b
	mov	a,d
	inx	b
	stax	b
	pop	psw
	pop	b
	ret
; Однократный патч входа: CALL func_ay_write_registers; LXI H,0x049D; SHLD 0x0101 (перенаправляет входной JMP 0x0100 на главный цикл 0x049D); PCHL (переход в 0x049D).
func_patch_entry_jump:
	call	func_ay_write_registers
	lxi	h,049dh
	shld	0101h
	pchl

; --- Code range: 055F ---
; Вычисление адреса XOR-слота: POP D (адрес возврата), slot=0x0700+2*lo(retaddr) (ADD E; MVI H,06; INX H); PUSH D; PUSH H (слот станет PC); XCHG; PCHL.
func_thunk_slot_addr:
	pop	d
	mov	a,e
	add	e
	mov	l,a
	mvi	h,06h
	inx	h
	push	d
	push	h
	xchg
	pchl
; XOR-цикл дешифровки 12-байтного слота ключом из 0x0553: LDAX D; XRA M; STAX D; INX H/D; DCR B; JNZ 0x056B. Хвост: LHLD 0x0103; POP PSW; POP D; RET — RET выталкивает адрес слота, PC уходит в расшифрованный трюк.
func_xor_decrypt_loop:
	push	psw
label_056B:
	ldax	d
	xra	m
	stax	d
	inx	h
	inx	d
	dcr	b
	jnz	label_056B
	lhld	var_cur_stream_ptr
	pop	psw
	pop	d
	ret
